#!/bin/sh
#
# beep - Make a beep sound.
#        Try pulseaudio first (package 'libpulse'),
#        use ALSA if that fails (package 'alsa-utils').
#
SOUND=/usr/local/share/sounds/beep.wav
paplay $SOUND 2>/dev/null || aplay -q $SOUND
